// Mock data for testing UI without database
export const mockUser = {
    id: "mock-user-1",
    name: "Demo User",
    email: "demo@gobuild.com",
    role: "SUPPLIER_ADMIN",
    supplierCompanyId: "mock-company-1",
};

export const mockCompany = {
    id: "mock-company-1",
    name: "Demo Suppliers Ltd",
    email: "contact@demosuppliers.com",
    phone: "+91 98765 43210",
    city: "Mumbai",
    state: "Maharashtra",
    gstNumber: "27XXXXX1234X1XX",
};

export const mockLeads = [
    {
        id: "1",
        title: "RCC for 5-story building",
        status: "QUALIFIED",
        estimatedValue: 5000000,
        probability: 75,
        expectedCloseDate: new Date("2025-12-31"),
        customerCompany: { name: "ABC Constructions" },
        assignedTo: { name: "Demo User" },
    },
    {
        id: "2",
        title: "Steel order for warehouse",
        status: "PROPOSAL",
        estimatedValue: 3500000,
        probability: 60,
        expectedCloseDate: new Date("2025-11-30"),
        customerCompany: { name: "XYZ Builders" },
        assignedTo: { name: "Demo User" },
    },
    {
        id: "3",
        title: "Cement supply for residential complex",
        status: "NEGOTIATION",
        estimatedValue: 2000000,
        probability: 80,
        expectedCloseDate: new Date("2025-10-15"),
        customerCompany: { name: "Prime Developers" },
        assignedTo: { name: "Demo User" },
    },
];

export const mockActivities = [
    {
        id: "1",
        type: "CALL",
        title: "Follow-up call with ABC Constructions",
        createdAt: new Date(),
        user: { name: "Demo User" },
        lead: {
            title: "RCC for 5-story building",
            customerCompany: { name: "ABC Constructions" },
        },
    },
    {
        id: "2",
        type: "MEETING",
        title: "Site visit scheduled",
        createdAt: new Date(Date.now() - 86400000),
        user: { name: "Demo User" },
        lead: {
            title: "Steel order for warehouse",
            customerCompany: { name: "XYZ Builders" },
        },
    },
];

export const mockQuotations = [
    {
        id: "1",
        quotationNumber: "QT1234567890",
        title: "RCC Supply Quote",
        status: "SENT",
        total: 5000000,
        validUntil: new Date("2025-12-31"),
        customerCompany: { name: "ABC Constructions" },
        items: [],
    },
];

export const mockInventory = [
    {
        id: "1",
        sku: "CEM001",
        name: "Portland Cement 50kg",
        description: "High-quality Portland cement suitable for all construction needs. Conforms to IS 269:2015 standards.",
        shortDescription: "Premium Portland cement for construction projects",
        category: "Cement",
        brand: "UltraTech",
        currentStock: 500,
        minStockLevel: 100,
        unit: "bags",
        costPrice: 350,
        sellingPrice: 420,
        images: [],
        primaryImage: null,
        isVisibleOnShop: true,
        isActive: true,
        specifications: JSON.stringify({
            "Grade": "53",
            "Strength": "53 MPa",
            "Standard": "IS 269:2015",
        }),
    },
    {
        id: "2",
        sku: "STL001",
        name: "TMT Bar 12mm",
        description: "High strength TMT bars with superior flexibility and corrosion resistance. Fe 500D grade.",
        shortDescription: "High strength TMT bars for reinforcement",
        category: "Steel",
        brand: "Tata Steel",
        currentStock: 45,
        minStockLevel: 50,
        unit: "tons",
        costPrice: 55000,
        sellingPrice: 62000,
        images: [],
        primaryImage: null,
        isVisibleOnShop: true,
        isActive: true,
        specifications: JSON.stringify({
            "Grade": "Fe 500D",
            "Diameter": "12mm",
            "Length": "12 meters",
        }),
    },
    {
        id: "3",
        sku: "SND001",
        name: "River Sand",
        description: "Clean river sand ideal for plastering and concrete work. Well graded and free from silt.",
        shortDescription: "Premium quality river sand for construction",
        category: "Sand",
        brand: null,
        currentStock: 150,
        minStockLevel: 30,
        unit: "cubic meter",
        costPrice: 1200,
        sellingPrice: 1500,
        images: [],
        primaryImage: null,
        isVisibleOnShop: true,
        isActive: true,
        specifications: JSON.stringify({
            "Type": "River Sand",
            "Grade": "Zone II",
            "Moisture": "<5%",
        }),
    },
];

export const mockDashboardStats = {
    totalLeads: 15,
    activeLeads: 8,
    wonLeads: 4,
    totalOrders: 12,
    pendingOrders: 3,
    totalRevenue: 15000000,
    totalCustomers: 8,
    lowStockItems: 2,
    conversionRate: "26.7",
};

export const mockRevenueData = [
    { month: "Jun 2025", revenue: 2500000 },
    { month: "Jul 2025", revenue: 3000000 },
    { month: "Aug 2025", revenue: 2800000 },
    { month: "Sep 2025", revenue: 3200000 },
    { month: "Oct 2025", revenue: 2900000 },
    { month: "Nov 2025", revenue: 3500000 },
];

export const mockLeadsByStatus = [
    { status: "NEW", count: 3 },
    { status: "CONTACTED", count: 2 },
    { status: "QUALIFIED", count: 3 },
    { status: "PROPOSAL", count: 2 },
    { status: "NEGOTIATION", count: 3 },
    { status: "WON", count: 4 },
    { status: "LOST", count: 2 },
];

// Mock Customers
export const mockCustomers = [
    {
        id: "cust-1",
        name: "ABC Constructions",
        email: "contact@abcconstructions.com",
        phone: "9876543210",
        contactPerson: "John Doe",
        address: "123, MG Road",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400001",
        gstNumber: "27ABCDE1234F1Z5",
        _count: {
            orders: 5,
            leads: 3,
            quotations: 4,
        },
    },
    {
        id: "cust-2",
        name: "XYZ Builders",
        email: "info@xyzbuilders.com",
        phone: "9876543211",
        contactPerson: "Jane Smith",
        address: "456, Park Street",
        city: "Delhi",
        state: "Delhi",
        pincode: "110001",
        gstNumber: "07XYZAB5678G2H3",
        _count: {
            orders: 3,
            leads: 2,
            quotations: 2,
        },
    },
    {
        id: "cust-3",
        name: "Prime Developers",
        email: "hello@primedev.com",
        phone: "9876543212",
        contactPerson: "Raj Kumar",
        address: "789, Brigade Road",
        city: "Bangalore",
        state: "Karnataka",
        pincode: "560001",
        gstNumber: "29PRIME1234K5L6",
        _count: {
            orders: 2,
            leads: 1,
            quotations: 1,
        },
    },
];

// Mock Orders
export const mockOrders = [
    {
        id: "ord-1",
        orderNumber: "ORD-20251120-0001",
        status: "CONFIRMED",
        paymentStatus: "PARTIAL",
        subtotal: 484000,
        taxPercent: 18,
        taxAmount: 87120,
        discount: 71120,
        total: 500000,
        paidAmount: 200000,
        deliveryDate: new Date("2025-12-15"),
        deliveryAddress: "Main Construction Site, Plot 42, Sector 5",
        deliveryNotes: "Deliver before 10 AM",
        customerCompany: {
            name: "ABC Constructions",
            contactPerson: "John Doe",
            phone: "9876543210",
            email: "contact@abcconstructions.com",
        },
        items: [
            {
                id: "item-1",
                itemName: "Portland Cement 50kg",
                description: "Premium quality cement",
                quantity: 500,
                unit: "bags",
                unitPrice: 420,
                total: 210000,
            },
            {
                id: "item-2",
                itemName: "TMT Bar 12mm",
                description: "High strength steel bars",
                quantity: 2,
                unit: "tons",
                unitPrice: 62000,
                total: 124000,
            },
            {
                id: "item-3",
                itemName: "River Sand",
                description: "Clean construction sand",
                quantity: 100,
                unit: "cubic meter",
                unitPrice: 1500,
                total: 150000,
            },
        ],
        createdAt: new Date("2025-11-20"),
    },
    {
        id: "ord-2",
        orderNumber: "ORD-20251119-0042",
        status: "IN_PROGRESS",
        paymentStatus: "PAID",
        subtotal: 300000,
        taxPercent: 18,
        taxAmount: 54000,
        discount: 0,
        total: 354000,
        paidAmount: 354000,
        deliveryDate: new Date("2025-12-10"),
        deliveryAddress: "Warehouse Site, Industrial Area",
        deliveryNotes: "Contact site manager before delivery",
        customerCompany: {
            name: "XYZ Builders",
            contactPerson: "Jane Smith",
            phone: "9876543211",
            email: "info@xyzbuilders.com",
        },
        items: [
            {
                id: "item-4",
                itemName: "TMT Bar 16mm",
                description: "Heavy duty steel bars",
                quantity: 5,
                unit: "tons",
                unitPrice: 60000,
                total: 300000,
            },
        ],
        createdAt: new Date("2025-11-19"),
    },
    {
        id: "ord-3",
        orderNumber: "ORD-20251118-0033",
        status: "DELIVERED",
        paymentStatus: "PAID",
        subtotal: 180000,
        taxPercent: 18,
        taxAmount: 32400,
        discount: 12400,
        total: 200000,
        paidAmount: 200000,
        deliveryDate: new Date("2025-11-25"),
        deliveryAddress: "Residential Complex, Block A",
        deliveryNotes: null,
        customerCompany: {
            name: "Prime Developers",
            contactPerson: "Raj Kumar",
            phone: "9876543212",
            email: "hello@primedev.com",
        },
        items: [
            {
                id: "item-5",
                itemName: "Portland Cement 50kg",
                description: "Premium quality cement",
                quantity: 400,
                unit: "bags",
                unitPrice: 420,
                total: 168000,
            },
            {
                id: "item-6",
                itemName: "River Sand",
                description: "Clean construction sand",
                quantity: 8,
                unit: "cubic meter",
                unitPrice: 1500,
                total: 12000,
            },
        ],
        createdAt: new Date("2025-11-18"),
    },
    {
        id: "ord-4",
        orderNumber: "ORD-20251115-0025",
        status: "PENDING",
        paymentStatus: "PENDING",
        subtotal: 450000,
        taxPercent: 18,
        taxAmount: 81000,
        discount: 0,
        total: 531000,
        paidAmount: 0,
        deliveryDate: new Date("2025-12-20"),
        deliveryAddress: "New Site, Highway 48",
        deliveryNotes: "Call 2 hours before delivery",
        customerCompany: {
            name: "ABC Constructions",
            contactPerson: "John Doe",
            phone: "9876543210",
            email: "contact@abcconstructions.com",
        },
        items: [
            {
                id: "item-7",
                itemName: "TMT Bar 12mm",
                description: "High strength steel bars",
                quantity: 7,
                unit: "tons",
                unitPrice: 62000,
                total: 434000,
            },
            {
                id: "item-8",
                itemName: "River Sand",
                description: "Clean construction sand",
                quantity: 10,
                unit: "cubic meter",
                unitPrice: 1600,
                total: 16000,
            },
        ],
        createdAt: new Date("2025-11-15"),
    },
];
